spring.application.name=ActivityPlanner
# Storage location for uploaded photos
upload.path=/home/pi/activity-photos/

spring.datasource.url=jdbc:h2:file:~/activityplanner_db

spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

spring.jpa.hibernate.ddl-auto=update

spring.h2.console.enabled=true

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
server.tomcat.max-parameter-count=1000
server.tomcat.max-part-count=100

# The ID of the specific shared sub-calendar
google.calendar.id=78f090a23ec62eaac904f17158a081b5d8fc8a796952c916e50f0672f4a9e4f3@group.calendar.google.com